#!/bin/bash

exec > >(tee >(systemd-cat -t on_reset_done)) 2>&1

send_line_notify() {
    curl -X POST -H "Authorization: Bearer DQD4JBTi18whWLvXDyIEJhn8KeihRdpJIBAdW1mPTLL" -F "message=$1" https://notify-api.line.me/api/notify               
}

ENV_PATH=/home/sun108/sun108-api/.env
TOUCH_CALIBRATION_FILE_PATH=/usr/lib/machine-config/touch-calibrations
STATE_DIR="/var/lib/hope-state"
STATE_FILE="$STATE_DIR/state"

MACHINE_TYPE=$(cat $ENV_PATH | grep MACHINE_TYPE | sed -e 's/^[[:space:]]*//' | sed 's/.*=//')
MACHINE_ID=$(cat $ENV_PATH | grep MACHINE_ID | sed -e 's/^[[:space:]]*//' | sed 's/.*=//')

echo "Got machine type $MACHINE_TYPE"
echo "Got machine id $MACHINE_ID"
send_line_notify "$(echo -e "on_reset_done called.\nMachine ID : $MACHINE_ID \nMachine type : $MACHINE_TYPE")"

# Ensure /var/lib/hope-state directory exists
if [ ! -d "$STATE_DIR" ]; then
   echo "Directory $STATE_DIR not found. Creating directory..."
   mkdir -p "$STATE_DIR"
   echo "Directory $STATE_DIR created."
else
   echo "Directory $STATE_DIR already exists. No action needed."
fi

echo "Reset machine config to factory"
remount-boot-rw
set-config-param /boot/hopeEnv.txt "extraboardargs" "drm.edid_firmware=HDMI-A-1:edid/1024x600_59.852hz.bin"
remount-boot-ro
#reboot

# Store factory reset state
echo "factory reset" > /var/lib/hope-state/state
echo "Factory reset state stored."
 
    
